In [96]:
import Pkg

In [97]:
# Pkg.add("Optim")

In [99]:
# Pkg.add("DelimitedFiles")

In [101]:
using DelimitedFiles

In [102]:
using Optim

In [103]:
X = readdlm("C:/Users/cosku/Desktop/Xfiles2.csv", ';', Float64);

In [104]:
Y = readdlm("C:/Users/cosku/Desktop/Yfiles2.csv", ';', Float64);

In [105]:
function LnL(bethas::Vector{Float64})
    sum = 0
    for i=1:length(Y)
        sum += -exp(X[i,:]'*bethas) + Y[i] * X[i,:]' * bethas - log(factorial(Y[i]))
    end
    return -sum;
end

LnL (generic function with 2 methods)

In [106]:
result = optimize(LnL, zeros(6), NelderMead())

 * Status: success

 * Candidate solution
    Final objective value:     1.427037e+03

 * Found with
    Algorithm:     Nelder-Mead

 * Convergence measures
    √(Σ(yᵢ-ȳ)²)/n ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    408
    f(x) calls:    660


In [107]:
fieldnames(typeof(result));

In [108]:
max_val_loglikelihood_nm = result.minimum

1427.0371769118456

In [109]:
betha_nm = result.minimizer

6-element Vector{Float64}:
  2.5339014771541692
 -0.03225537174807412
  0.11569857858474339
 -0.3540359087242927
  0.07982798904201631
 -0.4094415617875796

In [110]:
result = optimize(LnL, zeros(6), BFGS())

 * Status: success

 * Candidate solution
    Final objective value:     1.427037e+03

 * Found with
    Algorithm:     BFGS

 * Convergence measures
    |x - x'|               = 0.00e+00 ≤ 0.0e+00
    |x - x'|/|x'|          = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 1.31e-07 ≰ 1.0e-08

 * Work counters
    Seconds run:   1  (vs limit Inf)
    Iterations:    30
    f(x) calls:    129
    ∇f(x) calls:   129


In [111]:
max_val_loglikelihood_bfgs = result.minimum

1427.0371769092526

In [112]:
betha_bfgs = result.minimizer

6-element Vector{Float64}:
  2.5339054447306473
 -0.032255306032090404
  0.1156984416969696
 -0.35403713793915986
  0.0798282476451521
 -0.40944272467129467

In [113]:
result = optimize(LnL, zeros(6), LBFGS())

 * Status: success

 * Candidate solution
    Final objective value:     1.427037e+03

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 6.55e-12 ≰ 0.0e+00
    |x - x'|/|x'|          = 2.58e-12 ≰ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 1.50e-07 ≰ 1.0e-08

 * Work counters
    Seconds run:   3  (vs limit Inf)
    Iterations:    89
    f(x) calls:    270
    ∇f(x) calls:   270


In [114]:
max_val_loglikelihood_lbfgs = result.minimum

1427.037176909253

In [115]:
betha_lbfgs = result.minimizer

6-element Vector{Float64}:
  2.533905444749026
 -0.03225530603194564
  0.11569844170727965
 -0.35403713798689235
  0.07982824761986457
 -0.4094427246400607